### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by hvr** [Atry/dsl#1]
I've just noticed that this package advertises compatiblity with `base >=4.7 && <5`, however GHC 7.10 disagrees:

```
Configuring library for do-notation-dsl-0.1.0.0..
Preprocessing library for do-notation-dsl-0.1.0.0..
Building library for do-notation-dsl-0.1.0.0..

src/Control/Dsl/Return.hs:8:14:
    Unsupported extension: TypeApplications
<<ghc: 217504448 bytes, 125 GCs, 7850338/24049864 avg/max bytes residency (7 samples), 52M in use, 0.001 INIT (0.001 elapsed), 0.041 MUT (0.041 elapsed), 0.230 GC (0.230 elapsed) :ghc>>
```

In my function as Hackage Trustee I've already fixed up the metadata for this release at https://hackage.haskell.org/package/do-notation-dsl-0.1.0.0/revisions/ to prevent the cabal solver from trying to build this package with compilers which don't support the `TypeApplications` extension.

SInce I've already fixed up the metadata there's no immediate need to upload a new release to fix the metadata; however please take this into account for future releases.

If you have any questions please let me know!

See  https://matrix.hackage.haskell.org/package/do-notation-dsl for current report.

**Comment by Atry** [comment]
Thank you for figuring out that. I learned a lot from you and other Trustees. Thank you all!

**Comment by hvr** [comment]
@Atry you're welcome!

Btw, I just performed the revision https://hackage.haskell.org/package/do-notation-dsl-0.1.0.1/revisions/ 

Please take into account that if there's a build failure showing up on  matrix.hackage.haskell.org, it's not enough to upload a new release such as `do-notation-dsl-0.1.0.2`  but you also need to perform a metaadata revision to correct the affected release on Hackage to prevent the cabal solver from backtracking to that release into an invalid build-plan.
